# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  premier:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo toto_var
                   echo bre_var
workflows:
  # Name the workflow "welcome"
  two-contexts:
    # Run the welcome/run job in its own container
    jobs:
      - premier:
          contexts:
            - toto
            - br√©
